version: '3'
services:
  janus:
    build:
      context: ..
      dockerfile: ./docker/develop.dockerfile
    ports:
      - "2000:2000"               # gdbserver
      - "7088:7088"               # HTTP transport
      - "8188:8188"               # WebSocket transport
      - "30000-30020:30000-30020" # WebRTC UDP
    volumes:
      - ./recordings:/recordings
    env_file: janus.plugin.conference.environment
    links:
      - vernemq
    working_dir: /build
    command: /opt/janus/bin/janus
    # command: gdbserver :2000 /opt/janus/bin/janus
    stdin_open: true
    tty: true
  vernemq:
    image: netologygroup/mqtt-gateway:v0.12.2
    ports:
      - "1883:1883"
      - "8080:8080"
    environment:
      APP_AUTHN_ENABLED: 0
      APP_AUTHZ_ENABLED: 0
      APP_STAT_ENABLED: 0
      APP_AGENT_LABEL: alpha
      APP_ACCOUNT_ID: mqtt-gateway.dev.svc.example.org
volumes:
  janus-conference-cargo: {}
